---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
matrix:
  os: [mac]
  files: ["test_multi_platform.py"]
runson: ${matrix.os}
pre:
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - python3 -m playwright install
  - npm install playwright --save-exact
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
testSuites:
  - python3 $files
post:
  - cat yaml/mac/.hyperexecute_matrix.yaml

jobLabel: [playwright-Python, mac, matrix]