---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 1
concurrency: 1
env:
  TARGET_OS: "MacOS Catalina"
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
pre:
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - python3 -m playwright install
  - npm install playwright --save-exact
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr 'def' "test_multi_platform.py"
testRunnerCommand: python3 $test
post:
  - cat yaml/mac/.hyperexecute_autosplits.yaml

jobLabel: [playwright-Python, mac, autosplit]