---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: win
autosplit: true
retryOnFailure: true
maxRetries: 1
concurrency: 1
env:
  TARGET_OS: "Windows 10"
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
pre:
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - playwright install
  - npm install playwright --save-exact
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr 'def' test_scenario_1.py
testRunnerCommand: python $test
post:
  - cat yaml/win/.hyperexecute_autosplits.yaml

jobLabel: [playwright-Python, win, autosplit]