---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
matrix:
  os: [win]
  files: ["test_scenario_1.py"]
runson: ${matrix.os}
pre:
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - playwright install
  - npm install playwright --save-exact
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
testSuites:
  - python $files
post:
  - cat yaml/win/.hyperexecute_matrix.yaml

jobLabel: [playwright-Python, win, matrix]